# Generated by Django 4.2.16 on 2024-12-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn_level',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring_level',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer_level',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter_level',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
